
name: Labeler
on: [issues]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      contents: read
      pull-requests: write

    steps:
      -name: echos issue content
      run: echo "Issue title: ${{ github.event.issue.title }}"
      -name: wtf
      run: echo "Issue body: ${{ github.event.issue.body }}"