name: echo issue

on: issues

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      run: echo "Issue title: ${{ github.event.issue.title }}"
      run: echo "Issue body: ${{ github.event.issue.body }}"