on:
  workflow_dispatch: # Put here!!
    workflow_call:
      inputs:
        username:
          description: 'A username passed from the caller workflow'
          default: 'john-doe'
          required: false
          type: string

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo "$GITHUB_CONTXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}