name: Test-Workflow

on: issues
  types:
    -labeled
    jobs:
    echo-details:
      runs-on: ubuntu-latest
      permissions:
        issues: read
        steps:
         run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"